language: node_js
node_js:
  - "lts/*"

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

before_install:
  - npm prune

script:
  - npm run test-coverage

after_success:
  - npm run test-coveralls